---
# == Work Dir for replicated log
- name: create work dir
  file: path={{ mesos_work_dir }} state=directory

# == Remove default configs
- name: Remove Default Mesos Configs
  file: state=absent path=/etc/mesos/

- name: Remove Mesos ZK File
  file: state=absent path=/etc/mesos/zk

- name: Remove Default Mesos-Master Config
  file: state=absent path=/etc/mesos-master/

- name: Remove Default Mesos-Slave Config
  file: state=absent path=/etc/mesos-slave/

# == Configure and recreate
- name: Mesos default config file
  template: src=conf-mesos.j2 dest=/etc/default/mesos
  notify:
    - Restart mesos-master
    - Restart mesos-slave

- name: Mesos Master config file
  template: src=conf-mesos-master.j2 dest=/etc/default/mesos-master
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"
  notify:
    - Restart mesos-master

- name: Mesos Slave config file
  template: src=conf-mesos-slave.j2 dest=/etc/default/mesos-slave
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"
  notify:
    - Restart mesos-slave

- name: Check if upstart exists
  stat: path=/etc/init/
  register: etc_init

- name: Mesos master upstart script
  template: src=init-mesos-master.j2 dest=/etc/init/mesos-master.conf
  when: (mesos_install_mode == "master" or mesos_install_mode == "master-slave") and etc_init.stat.exists == true
  notify:
    - Restart mesos-master

- name: Mesos slave upstart script
  template: src=init-mesos-slave.j2 dest=/etc/init/mesos-slave.conf
  when: (mesos_install_mode == "slave" or mesos_install_mode == "master-slave") and etc_init.stat.exists == true
  notify:
    - Restart mesos-slave
    
- name: Check if systemd exists
  stat: path=/usr/lib/systemd/system/
  register: systemd_check
  
- name: Mesos master systemd script
  template: src=mesos-master.service.j2 dest=/usr/lib/systemd/system/mesos-master.service
  when: (mesos_install_mode == "master" or mesos_install_mode == "master-slave") and systemd_check.stat.exists == true
  notify:
    - Reload daemon
    - Restart mesos-master

- name: Mesos slave systemd script
  template: src=mesos-slave.service.j2 dest=/usr/lib/systemd/system/mesos-slave.service
  when: (mesos_install_mode == "slave" or mesos_install_mode == "master-slave") and systemd_check.stat.exists == true
  notify:
    - Reload daemon
    - Restart mesos-slave

# == Start and enable service
- name: Start and enable mesos master service
  service: name=mesos-master state=started enabled=yes
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"

- name: Start and enable mesos slave service
  service: name=mesos-slave state=started enabled=yes
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"

- name: Stop and disable mesos slave on master
  service: name=mesos-slave state=stopped enabled=no
  when: mesos_install_mode == "master"

- name: Stop and disable mesos master on slave
  service: name=mesos-master state=stopped enabled=no
  when: mesos_install_mode == "slave"

- name: Stop and disable zookeeper on mesos slave
  service: name=zookeeper state=stopped enabled=no
  when: mesos_install_mode == "slave"
